Add reference to charts-repo-actions-demo
helm/chart-testing pull request #281
Opened 2020-10-01 19:14 UTC by nvtkaszpir

**What this PR does / why we need it**:

Referencing charts-repo-actions-demo in docs should be beneficial for those
looking for more in-depth examples of how to use ct tool.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

Fixes #241

**Special notes for your reviewer**:

2020-10-06 17:15 UTC, nvtkaszpir commented
ping @rimusz @unguiculus

2020-10-06 17:32 UTC, rimusz commented
/lgtm

2020-10-07 21:57 UTC, davidkarlsen approved these changes

2020-10-10 19:52 UTC, unguiculus requested changes

2020-10-10 19:52 UTC, unguiculus commented on README.md
> +For more extensive how-to guide it is recommended to see:
I'd suggest to reword this:

```suggestion
For a more extensive how-to guide, please see:

```

2020-10-15 19:14 UTC, nvtkaszpir commented
slight ping towards @unguiculus

2020-10-15 19:45 UTC, unguiculus approved these changes

2020-10-15 19:45 UTC, merged