Move to gh-actions
helm/chart-testing pull request #297
Opened 2020-11-06 09:55 UTC by davidkarlsen

Fixes #296 

* Release is now a workflow dispatch
* Upgrade to helm v3.4.0

Note: For release to work the secrets for quay needs to be defined: QUAY_USERNAME + QUAY_PASSWORD

2020-11-09 18:24 UTC, davidkarlsen commented
@unguiculus @scottrigby ptal?

2020-11-09 20:15 UTC, unguiculus requested changes
In general, I think it would be a good idea to have the same setup for both, chart-testing and chart-releaser. I went a different route for chart-releaser but don't really have strong opinions. Since chart-releaser's move to GitHub actions we've been having issues with Go modules because go.mod and go.sum would change during the build which I could not reproduce locally. This doesn't seem to be the case here. Have you experienced any such issues? If not, it may make more sense to proceed with your setup and adjust that of chart-releaser.

2020-11-09 20:15 UTC, unguiculus commented on .github/workflows/release.yaml
> +          prerelease: false
This should be removed. GoReleaser creates the release.

2020-11-09 20:15 UTC, unguiculus commented on .github/workflows/release.yaml
> +          password: ${{ secrets.QUAY_PASSWORD }}
Previously, we had DOCKER_USERNAME and DOCKER_PASSWORD. I'd prefer these. We will have to add the secrets.

2020-11-09 21:41 UTC, davidkarlsen commented
> In general, I think it would be a good idea to have the same setup for both, chart-testing and chart-releaser. I went a different route for chart-releaser but don't really have strong opinions. Since chart-releaser's move to GitHub actions we've been having issues with Go modules because go.mod and go.sum would change during the build which I could not reproduce locally. This doesn't seem to be the case here. Have you experienced any such issues? If not, it may make more sense to proceed with your setup and adjust that of chart-releaser.

I haven't had problems with go.{mod,sum} changing unexpectedly (or at all) - so I though I'd leave them in as a security-measure - we can remove them if we see any trouble down the lane.

2020-11-23 17:07 UTC, davidkarlsen commented
@unguiculus wdyt - can we merge it now?

2020-11-24 06:35 UTC, unguiculus approved these changes

2020-11-24 06:36 UTC, merged

2020-11-24 06:37 UTC, unguiculus commented
I disabled the old Circle CI project.