Chore/target branch main
helm/chart-testing pull request #510
Opened 2023-01-06 16:00 UTC by fty4

**What this PR does / why we need it**:

Because the default branch on GitHub is [`main`](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) and not longer `master` this should also be the default to chart-testing.

**Which issue this PR fixes**:

fixes #376 

**Special notes for your reviewer**:

BREAKING CHANGE:
If e.g an action or workflow is not using an explicit specified `target-branch` the job might will fail after this change.

But after this change new users does not have the problem that a wrong branch is used.
For example I was suffering with the error message `exit status 128`- see #330 because the default branch was not `main`.

2023-02-09 20:54 UTC, thisisrachelramos approved these changes
<img src="https://media1.giphy.com/media/8JVjMCr3OIAhO/giphy.gif"/>

2023-07-06 08:12 UTC, cpanato commented
@fty4 can you rebase and update the docs? thanks for this PR

2023-07-17 12:06 UTC, fty4 commented
@cpanato I've updated the docs and forced-pushed the rebased commits.
<sub><sup>(Required multiple force-push because of DCO)</sup></sub>

2023-07-17 12:08 UTC, cpanato commented
this will be a breaking change for existing users, if they dont set the --target-branch in the config

2023-07-17 12:35 UTC, fty4 commented
That is true - I already mentioned this in the PR body.

New users will still have to specify the parameter if this will not be changed.

2023-08-16 00:29 UTC, joejulian approved these changes

2023-08-16 07:12 UTC, cpanato commented
when we release I will make a note in the release notes for this

2023-08-18 09:22 UTC, cpanato requested changes
small request

2023-08-18 09:22 UTC, cpanato commented on examples/kind/README.md
> +It creates a cluster with a single main node and one worker node.
```suggestion
It creates a cluster with a single control-plane node and one worker node.
```

2023-09-07 06:17 UTC, odysseu approved these changes

2023-10-04 06:52 UTC, odysseu approved these changes

2023-10-04 06:53 UTC, odysseu commented
LGTM 👍

2023-10-04 08:38 UTC, jouve commented
this can be tested [here](https://github.com/jouve/chart-testing/releases) with 
* https://github.com/helm/chart-testing/pull/601
* https://github.com/helm/chart-testing/pull/591
* https://github.com/helm/chart-testing/pull/510
* https://github.com/helm/chart-testing/pull/508

2023-11-19 11:43 UTC, cpanato approved these changes
lgtm

2023-11-19 11:56 UTC, davidkarlsen commented
Lgtm. We can maybe bump version number a bit to signal breaking change.

2023-11-19 12:13 UTC, davidkarlsen approved these changes

2023-11-19 12:32 UTC, cpanato commented
> Lgtm. We can maybe bump version number a bit to signal breaking change.

yes

2023-11-19 12:32 UTC, cpanato commented
let marinate this in the main branch for a while

2023-11-19 12:33 UTC, merged