allow reuse-values on upgrade to be configurable
helm/chart-testing pull request #531
Opened 2023-03-11 00:44 UTC by joejulian

**What this PR does / why we need it**:

many charts add new values between chart versions. When using the reuse-values flag, those charts fail because reuse-values ignores the default values file.

By making this configurable, it allows the chart maintainer to determine whether it's appropriate for their chart to add new values when upgrading.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #525 

**Special notes for your reviewer**:

2023-03-24 12:01 UTC, cpanato requested changes
lgtm, thanks for this PR
but will need to update the docs and fix the test, can you do that?

2023-06-14 16:10 UTC, stgrace commented
Hey @joejulian,

Have you gotten a chance to look at this yet? Would like for this PR to get merged, because any chart adding new values basically fails on testing because of this at the moment.
I could also take a look at it if you want me to.

Kind regards

2023-08-16 00:31 UTC, joejulian commented
I'm going to close this for now. I'll re-do it when the --reset-and-reuse flag is added to helm.

2023-08-16 00:31 UTC, closed without merging

2024-01-10 18:09 UTC, AndrewSirenko commented
@joejulian now that [feat(helm): Add --reset-then-reuse-values flag to 'helm upgrade' #9653](https://github.com/helm/helm/pull/9653) was merged, would you want to re-open this issue? Or would you prefer me open a new issue?

2024-01-10 20:28 UTC, joejulian commented
> @joejulian now that [feat(helm): Add --reset-then-reuse-values flag to 'helm upgrade' #9653](https://github.com/helm/helm/pull/9653) was merged, would you be able to re-open the PR? Or would you prefer me to help update docs + add test?  

Yes, I'll work on that in the next week.

2024-02-28 11:06 UTC, ppawlowski commented
Is there a plan to bring this up to the table again?