use .helmignore when identifying changed charts
helm/chart-testing pull request #591
Opened 2023-08-31 20:31 UTC by jouve

**What this PR does / why we need it**:

use .helmignore when identifying changed charts.

The use helmignore is disabled by default (current behaviour) and enabled with `--use-helmignore`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #530

**Special notes for your reviewer**:

pkg/ignore/rules.go is an exact copy of https://github.com/helm/helm/blob/main/internal/ignore/rules.go

the FilterFiles function is adapted from https://github.com/helm/helm/blob/main/pkg/chart/loader/directory.go#L46

2023-11-19 09:19 UTC, jouve commented
Up

2024-03-06 22:43 UTC, jouve commented
up

2024-04-21 07:13 UTC, davidkarlsen reviewed
sorry for the late response.
can you rebase so we get a new build and see if the docs step passes?

2024-04-24 21:47 UTC, davidkarlsen commented
please regen the docs and check in and it will pass

2024-04-29 15:26 UTC, cpanato requested changes
seems ok so far, but did not look in depth, i need a bit more time

2024-04-29 15:26 UTC, cpanato commented on pkg/ignore/ignore_test.go
> +package ignore
add the boilerplate header

2024-05-21 08:07 UTC, cpanato approved these changes

2024-05-22 08:17 UTC, merged

2025-01-06 11:44 UTC, mnonnenmacher commented
@cpanato Could you please make a release with this feature? It's confusing that the `--use-helmignore` option is mentioned in the docs but not available in the latest version.

2025-01-13 12:28 UTC, cpanato commented
@mnonnenmacher released https://github.com/helm/chart-testing/releases/tag/v3.12.0

2025-01-13 15:09 UTC, mnonnenmacher commented
@cpanato Great, thank you!